import { useState, useEffect } from "react";

import noteService from "./services/notes";

import Note from "./Note";
//import axios from "axios";

const App = () => {
  //1.we need to get data from server
  //2.const [notes, setNotes] = useState([]) this source will be the data we get from server

  /*Things we need to setup
    1.backend server: will create fake backend server
    2.in the frontend code, read the data from backend server
     2.1 npm library that provides technology to call backend server
     2.2 where and how to call this library from react code
   */

  const [notes, setNotes] = useState([]);
  const [newNote, setnewNote] = useState("a new note");
  const [showAll, setshowAll] = useState(true);

  // const toggleImportanceOf = (id) => {
  //   const url = `http://localhost:3001/notes/${id}`;
  //   const note = notes.find((n) => n.id === id);

  //   const changedNote = { ...note, important: !note.important };
  //   noteService
  //     .update(id, changedNote)
  //     .then((response) => {
  //       setNotes(notes.map((note) => (note.id !== id ? note : response.data)));
  //     })
  //     .catch((error) => {
  //       alert(`the note '${note.content}' was already deleted from server`);
  //       setNotes(notes.filter((n) => n.id !== id));
  //     });
  //   console.log(`importance of ${id} needs to be toggled`);
  // };

  // axios.put(url, changedNote).then((response) => {
  //   setNotes(notes.map((note) => (note.id !== id ? note : response.data)));
  // });

  useEffect(() => {
    noteService.getAll().then((response) => {
      setNotes(response.data);
    });
    //axios.get("http://localhost:3001/notes").then((Response) => {
    //   setNotes(Response.data);
    //   console.log(Response);
    // });
  }, []);

  const addNote = (event) => {
    event.preventDefault();

    let noto = {
      //id: notes.length + 1,
      content: newNote,
      date: new Date().toISOString(),
      important: Math.random() < 0.5 ? true : false,
    };

    // axios.post(`http://localhost:3001/notes`, noto).then((response) => {
    //=>'.get' get the all notes, '.post' create a note, '.put' update data for existing new note with id
    // console.log(response);
    //=>json server library uses backend server so from now id is generated by backend data as well create a new note
    // setNotes(notes.concat(response.data));
    // setnewNote("");
    // });

    // console.log("button clicked", event.target);
    // setNotes([...notes, note]);
    // setnewNote(" ");

    noteService.create(noto).then((response) => {
      setNotes(notes.concat(response.data));
      setnewNote("");
    });

    // axios.post("http://localhost:3001/notes", note).then((Response) => {
    //   console.log(Response.data);
    //   setNotes([...notes, Response.data]);
    //   setnewNote(" ");
    // });
  };

  const handleNoteChange = (event) => {
    setnewNote(event.target.value);
  };

  const random = () => setshowAll(!showAll);

  const notesToShow = showAll
    ? notes
    : notes.filter((tog) => tog.important === true);

  return (
    <>
      <h1>Notes</h1>
      {/* </><button onClick={() => setshowAll(!showAll)}> */}
      <button onClick={random}>show {showAll ? "All" : "Important"}</button>
      <ul>
        {notesToShow.map((notex) => (
          <Note
            key={notex.id}
            note={notex}
            toggleImportance={() => {
              //toggleImportanceOf(note.id)

              console.log(
                `button is clicked by function passed from API for id ${notex.id}`
              );
              //1.make new object from current note with toggled importand field
              const updatedNote = { ...notex, important: !notex.important };
              //2.update backend server with the updated object
              //axios.put(`http://localhost:3001/notes/${notex.id}`, updatedNote)
              noteService.update(notex.id, updatedNote).then((response) => {
                console.log(response.data);
                //3.now, also update the frontend state with the updated note
                setNotes(
                  notes.map((x) => (x.id !== notex.id ? x : response.data))
                );
              });
            }}
          />
        ))}
      </ul>
      <form onSubmit={addNote}>
        <input value={newNote} onChange={handleNoteChange} />
        <button type="submit">submit</button>
      </form>
    </>
  );
};

export default App;
